name: "Deploy WordPress projects to WP Engine"
branding:
  icon: "upload-cloud"
  color: "purple"
description: "Deploy WordPress projects to WP Engine"
inputs:
  WPE_SSHG_KEY_PRIVATE:
    description: "The private RSA key you will save in the Github Secrets"
    required: true
  PHP_LINT:
    description: "optional php syntax check"
    required: false
    default: false
  FLAGS:
    description: "Optional flags for the deployment"
    required: true
    default: '-azvr --inplace --exclude=".*"'
  CACHE_CLEAR:
    description: "Optional WPE Clear cache"
    required: false
    default: true
  TPO_SRC_PATH:
    description: "An optional source directory to deploy other than the root directory that is being versioned."
    default: "."
    required: false
  TPO_PATH:
    description: "An optional destination directory to deploy to other than the WordPress root."
    default: ""
    required: false
  PRD_BRANCH:
    description: "Source branch to deploy PRD_ENV"
    required: true
    default: "PROD_BRANCH_HERE"
  PRD_ENV:
    description: "Destination to deploy to WPE Prod"
    required: true
    default: "PROD_ENV_HERE"
  STG_BRANCH:
    description: "Source branch to deploy STG_ENV"
    required: false
    default: "STAGE_BRANCH_HERE"
  STG_ENV:
    description: "Destination to deploy to WPE Stage"
    required: false
    default: "STAGE_ENV_HERE"
  DEV_BRANCH:
    description: "Source branch to deploy DEV_ENV"
    required: false
    default: "DEV_BRANCH_HERE"
  DEV_ENV:
    description: "Destination to deploy to WPE Dev"
    required: false
    default: "DEV_ENV_HERE"
  SCRIPT:
    description: "File containing custom scripts run after the rsync"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
